# -*- coding: utf-8 -*-
"""Research_paper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0HjZNOJ6B79R0R0O73PDWvDVbkKEiYo

# This is the code for the paper titled: Linear vs. Non-Linear Return Forecasting: A Dual Evaluation of Predictive Accuracy and Economic Value

This code includes:
* Data handling and pre-processing.

Import relevant libraries
"""

import pandas as pd
import numpy as np
from pathlib import Path
import itertools
from pandas.tseries.offsets import YearEnd, YearBegin, MonthBegin, DateOffset
from google.colab import drive
drive.mount("/content/drive")

!pip install ipca

"""Shared functions"""

# ==============================================================================
# OPTIMIZING DATAFRAME MEMORY SPACE
# ==============================================================================
# Optimizing memory usage
def optimize_df(df, cat_threshold=0.5, verbose=True):
    """
    Optimises a pandas DataFrame to reduce RAM usage.
    - Downcasts numerical columns.
    - Converts repeated object columns to categoricals.
    - Stores boolean columns efficiently.
    """
    df = df.copy()

    start_mem = df.memory_usage(deep=True).sum() / 1024**2

    for col in df.columns:
        col_dtype = df[col].dtype

        # Downcast floats
        if pd.api.types.is_float_dtype(col_dtype):
            df[col] = pd.to_numeric(df[col], downcast="float")

        # Downcast floats
        elif pd.api.types.is_integer_dtype(col_dtype):
            df[col] = pd.to_numeric(df[col], downcast="integer")

        # Convert object columns
        elif pd.api.types.is_object_dtype(col_dtype):
            num_unique = df[col].nunique()
            num_total = len(df[col])

            if num_total > 0 and num_unique / num_total < cat_threshold:
                df[col] = df[col].astype("category")

        # Handle boolean types
        elif pd.api.types.is_bool_dtype(col_dtype):
            df[col] = df[col].astype(bool)

    end_mem = df.memory_usage(deep=True).sum() / 1024**2

    if verbose:
        reduction = 100 * (start_mem - end_mem) / start_mem if start_mem > 0 else 0
        print(
            f"Memory usage reduced from {start_mem:.2f} MB to {end_mem:.2f} MB "
            f"({reduction:.1f}% reduction).")

    return df

# ==============================================================================
# FUNCTIONS FOR MODELS
# ==============================================================================
# ------------------------------------------------------------------------------
# Global
# ------------------------------------------------------------------------------
# Base directory
BASE_DIR = Path("/content/drive/My Drive/Master thesis")

# Loading files
def load_excel(filename, **kwargs):
    return pd.read_excel(BASE_DIR / filename, **kwargs)

def load_csv(filename, **kwargs):
    return pd.read_csv(BASE_DIR / filename, **kwargs)

def load_parquet(filename, **kwargs):
    return pd.read_parquet(BASE_DIR / filename, **kwargs)

# Saving files
def save_excel(df, filename, **kwargs):
    return df.to_excel(BASE_DIR / filename, **kwargs)

def save_csv(df, filename, **kwargs):
    return df.to_csv(BASE_DIR / filename, **kwargs)

def save_parquet(df, filename, **kwargs):
    return df.to_parquet(BASE_DIR / filename, **kwargs)

# Full characteristics list
char_cols = [
    "prc", "market_equity", "div12m_me", "chcsho_12m", "eqnpo_12m", "ret_1_0",
    "ret_3_1", "ret_6_1", "ret_9_1", "ret_12_1", "ret_12_7", "ret_60_12",
    "seas_1_1an", "seas_1_1na", "seas_2_5an", "seas_2_5na", "seas_6_10an",
    "seas_6_10na", "seas_11_15an", "seas_11_15na", "seas_16_20an",
    "seas_16_20na", "at_gr1", "sale_gr1", "capx_gr1", "inv_gr1", "debt_gr3",
    "sale_gr3", "capx_gr3", "inv_gr1a", "lti_gr1a", "sti_gr1a", "coa_gr1a",
    "col_gr1a", "cowc_gr1a", "ncoa_gr1a", "ncol_gr1a", "nncoa_gr1a", "fnl_gr1a",
    "nfna_gr1a", "tax_gr1a", "be_gr1a", "ebit_sale", "gp_at", "cop_at",
    "ope_be", "ni_be", "ebit_bev", "netis_at", "eqnetis_at", "dbnetis_at",
    "oaccruals_at", "oaccruals_ni", "taccruals_at", "taccruals_ni", "noa_at",
    "opex_at", "at_turnover", "sale_bev", "rd_sale", "cash_at", "sale_emp_gr1",
    "emp_gr1", "ni_inc8q", "noa_gr1a", "ppeinv_gr1a", "lnoa_gr1a", "capx_gr2",
    "saleq_gr1", "niq_be", "niq_at", "niq_be_chg1", "niq_at_chg1", "rd5_at",
    "dsale_dinv", "dsale_drec", "dgp_dsale", "dsale_dsga", "saleq_su", "niq_su",
    "capex_abn", "op_atl1", "gp_atl1", "ope_bel1", "cop_atl1", "pi_nix",
    "ocf_at", "op_at", "ocf_at_chg1", "at_be", "ocfq_saleq_std", "tangibility",
    "earnings_variability", "aliq_at", "f_score", "o_score", "z_score",
    "kz_index", "ni_ar1", "ni_ivol", "at_me", "be_me", "debt_me", "netdebt_me",
    "sale_me", "ni_me", "ocf_me", "fcf_me", "eqpo_me", "eqnpo_me", "rd_me",
    "ival_me", "bev_mev", "ebitda_mev", "aliq_mat", "eq_dur", "beta_60m",
    "resff3_12_1", "resff3_6_1", "mispricing_mgmt", "mispricing_perf",
    "ivol_capm_21d", "iskew_capm_21d", "coskew_21d", "beta_dimson_21d",
    "ivol_ff3_21d", "iskew_ff3_21d", "ivol_hxz4_21d", "iskew_hxz4_21d",
    "rmax5_21d", "rmax1_21d", "rvol_21d", "rskew_21d", "zero_trades_21d",
    "dolvol_126d", "dolvol_var_126d", "turnover_126d", "turnover_var_126d",
    "zero_trades_126d", "zero_trades_252d", "ami_126d", "ivol_capm_252d",
    "prc_highprc_252d", "betadown_252d", "bidaskhl_21d", "corr_1260d",
    "betabab_1260d", "rmax5_rvol_21d", "age", "qmj", "qmj_prof", "qmj_growth",
    "qmj_safety"]

# Dataframe metrics
def print_dataframe_summary(df):
    total_rows = df.shape[0]
    total_observations = df.size
    total_na = df.isna().sum().sum()
    valid_observations = total_observations - total_na

    print(f"Total rows: {total_rows}")
    print(f"Total observations: {total_observations}")
    print(f"Total missing (NaN) values: {total_na}")
    print(f"Total valid (non-NaN) values: {valid_observations}")

# Creating industry dummies
def add_sic_dummies(df, sic_col="sic", prefix="sic"):
    if sic_col not in df.columns:
        raise ValueError(f"Column \"{sic_col}\" not found in dataframe.")

    df = df.copy()

    df["sic_first_two"] = df[sic_col].astype(str).str[:2]
    df.loc[df[sic_col].astype(str).str.lower().isin(["sic_na", "nan", "none"]), "sic_first_two"] = pd.NA

    initial_rows = len(df)
    df = df[df["sic_first_two"].notna()].copy()
    rows_dropped = initial_rows - len(df)

    sic_dummies = pd.get_dummies(df["sic_first_two"], prefix=prefix, drop_first=False)
    df = pd.concat([df, sic_dummies], axis=1)

    df = df.drop(columns=["sic_first_two"])

    print(f"SIC dummy variables created: {sic_dummies.shape[1]}")
    print(f"Rows dropped due to missing or invalid SIC codes: {rows_dropped}")
    print(f"Final dataframe shape: {df.shape}")

    return df

# Dropping missing rows
def drop_missing_rows(df, column_to_check):
    """
    Drops rows where `column_to_check` is missing.
    """
    df = df.copy()

    if column_to_check not in df.columns:
        print(f"Warning: Column \"{column_to_check}\" not found. No rows dropped.")
        return df

    initial_rows = len(df)

    df_cleaned = df.dropna(subset=[column_to_check])

    final_rows = len(df_cleaned)
    rows_dropped = initial_rows - final_rows
    percentage_dropped = (rows_dropped / initial_rows) * 100 if initial_rows > 0 else 0

    print(f"Initial number of rows: {initial_rows}")
    print(f"Rows dropped where \"{column_to_check}\" was missing: {rows_dropped}")
    print(f"Percentage of rows dropped: {percentage_dropped:.2f}%")
    print(f"Final number of rows: {final_rows}")

    return df_cleaned

# Imputing missing values
def impute_monthly_median(df, characteristic_cols, date_col="date", fill_remaining=0, group_by_month=True):
    """
    Imputes missing characteristic values using the cross-sectional median
    within each month/date. Any remaining missing values are filled with 0.
    """
    df = df.copy()

    if date_col not in df.columns:
        raise ValueError(f"Column \"{date_col}\" not found in dataframe.")

    df[date_col] = pd.to_datetime(df[date_col])

    valid_characteristic_cols = [
        col for col in characteristic_cols
        if col in df.columns]

    missing_cols = [
        col for col in characteristic_cols
        if col not in df.columns]

    if missing_cols:
        print(f"{len(missing_cols)} characteristic columns not found in dataframe and skipped.")

    if not valid_characteristic_cols:
        raise ValueError("No valid characteristic columns found for imputation.")

    group_col = "_month" if group_by_month else date_col

    if group_by_month:
        df[group_col] = df[date_col].dt.to_period("M")

    monthly_medians = (
        df.groupby(group_col)[valid_characteristic_cols]
          .transform("median"))

    df[valid_characteristic_cols] = (
        df[valid_characteristic_cols]
        .fillna(monthly_medians)
        .fillna(fill_remaining))

    if group_by_month:
        df = df.drop(columns=group_col)

    print("Monthly median imputation complete.")
    print(f"Imputed characteristic columns: {len(valid_characteristic_cols)}")
    print(f"Remaining NaNs in characteristic columns: {df[valid_characteristic_cols].isna().sum().sum()}")

    return df

# Rank normalization [-1,1]
def rank_normalize_characteristics(df, characteristic_cols, date_col="date", method="average"):
    """
    Rank-normalizes firm characteristics cross-sectionally by date.
    Each characteristic is ranked within each date and transformed to [-1, 1]:
        2 * rank(C_{s,it-1}) / (N_t + 1) - 1
    where N_t is the number of non-missing observations for that characteristic
    in that period.
    """
    df = df.copy()

    if date_col not in df.columns:
        raise ValueError(f"Column \"{date_col}\" not found in dataframe.")

    df[date_col] = pd.to_datetime(df[date_col])

    valid_characteristic_cols = [
        col for col in characteristic_cols
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col])]

    missing_cols = [
        col for col in characteristic_cols
        if col not in df.columns]

    if missing_cols:
        print(f"{len(missing_cols)} characteristic columns not found and skipped.")

    if not valid_characteristic_cols:
        raise ValueError("No valid numeric characteristic columns found for rank normalization.")

    print(f"Rank-normalizing {len(valid_characteristic_cols)} characteristic columns by {date_col}.")

    for col in valid_characteristic_cols:
        df[col] = df.groupby(date_col)[col].transform(
            lambda x: 2 * x.rank(method=method, na_option="keep") / (x.notna().sum() + 1) - 1)

    print("Rank normalization complete.")
    print(f"Remaining NaNs in transformed columns: {df[valid_characteristic_cols].isna().sum().sum()}")

    return df

# Sample split scheme
def rolling_train_val_test_yearly(df, date_col="date", start_train="1970-01-01", end_train="1986-12-31", val_years=12):
    """
    Creates yearly rolling train-validation-test splits, where:
    - The training window starts fixed and expands by one year each iteration.
    - The validation window has a fixed length and rolls forward each iteration.
    - The test window is fixed at one calendar year.
    """
    df = df.copy()

    if date_col not in df.columns:
        raise ValueError(f"Column \"{date_col}\" not found in dataframe.")

    df[date_col] = pd.to_datetime(df[date_col])
    last_date = df[date_col].max()

    train_start_date = pd.to_datetime(start_train)
    train_end_date = pd.to_datetime(end_train)

    while True:
        val_start_date = train_end_date + YearBegin(1)
        val_end_date = val_start_date + DateOffset(years=val_years) - pd.Timedelta(days=1)

        test_start_date = val_end_date + MonthBegin(1)
        test_end_date = test_start_date + YearEnd(1)

        if test_end_date > last_date:
            break

        yield (
            train_start_date,
            train_end_date,
            val_start_date,
            val_end_date,
            test_start_date,
            test_end_date)

        train_end_date += YearEnd(1)

# Newey-West standard errors
def newey_west_se(x, lags=4):
    """
    Computes the Newey-West standard error of the sample mean.
    """
    x = pd.Series(x).dropna().astype(float)
    T = len(x)

    if T == 0:
        return np.nan

    lags = max(0, min(lags, T - 1))

    x_demeaned = x - x.mean()

    gamma_0 = np.sum(x_demeaned.values * x_demeaned.values) / T
    long_run_var = gamma_0

    for lag in range(1, lags + 1):
        weight = 1 - lag / (lags + 1)
        gamma_lag = np.sum(
            x_demeaned.iloc[lag:].values * x_demeaned.iloc[:-lag].values) / T
        long_run_var += 2 * weight * gamma_lag

    return np.sqrt(long_run_var / T)

# ------------------------------------------------------------------------------
# Performance evaluation metrics
# ------------------------------------------------------------------------------
# Out-of-sample R^2
def r2_oos(y_true, y_pred, benchmark_pred=None, lags=4):
    """
    Computes the out-of-sample R^2 following Gu et al., (2020).
    """
    y_true = pd.Series(y_true).astype(float).reset_index(drop=True)
    y_pred = pd.Series(y_pred).astype(float).reset_index(drop=True)

    if benchmark_pred is None:
        benchmark_pred = pd.Series(np.zeros(len(y_true)))
    else:
        benchmark_pred = pd.Series(benchmark_pred).astype(float).reset_index(drop=True)

    data = pd.DataFrame({
        "y_true": y_true,
        "y_pred": y_pred,
        "benchmark_pred": benchmark_pred}).dropna()

    y = data["y_true"]
    pred = data["y_pred"]
    bench = data["benchmark_pred"]

    model_error = y - pred
    benchmark_error = y - bench

    denominator = np.sum(benchmark_error ** 2)

    if denominator == 0:
        r2_oos = np.nan
    else:
        r2_oos = 1.0 - np.sum(model_error ** 2) / denominator

    loss_diff = benchmark_error ** 2 - model_error ** 2

    mean_loss_diff = loss_diff.mean()
    nw_se = newey_west_se(loss_diff, lags=lags)
    t_stat = mean_loss_diff / nw_se if nw_se > 0 else np.nan

    return {
        "r2_oos": r2_oos,
        "mean_loss_diff": mean_loss_diff,
        "nw_se": nw_se,
        "t_stat": t_stat,
        "n_obs": len(data),
        "lags": lags}

# Adjusted Diebold-Mariano statistic
def dm_test(df, y_true_col, model_pred_cols, date_col="year_month", lags=4, pairs=None):
    """
    Computes the adjusted pairwise Diebold-Mariano statistic following Gu et al., (2020)
    """
    df = df.copy()

    if y_true_col not in df.columns:
        raise ValueError(f"Column \"{y_true_col}\" not found in dataframe.")

    if date_col not in df.columns:
        raise ValueError(f"Column \"{date_col}\" not found in dataframe.")

    missing_pred_cols = [
        col for col in model_pred_cols.values()
        if col not in df.columns]

    if missing_pred_cols:
        raise ValueError(f"Prediction columns not found: {missing_pred_cols}")

    df[date_col] = pd.to_datetime(df[date_col].astype(str)).dt.to_period("M")

    model_names = list(model_pred_cols.keys())

    if pairs is None:
        pairs = list(itertools.combinations(model_names, 2))

    squared_errors = {}

    for model_name, pred_col in model_pred_cols.items():
        squared_errors[model_name] = (
            df[y_true_col] - df[pred_col]) ** 2

    monthly_diffs = {}

    for model_a, model_b in pairs:
        diff_name = f"dbar_{model_a}_{model_b}"

        loss_diff = squared_errors[model_a] - squared_errors[model_b]

        monthly_diffs[diff_name] = (
            loss_diff
            .groupby(df[date_col])
            .mean())

    dm_monthly = pd.DataFrame(monthly_diffs).sort_index()

    dm_results = []

    for model_a, model_b in pairs:
        col = f"dbar_{model_a}_{model_b}"
        x = dm_monthly[col].dropna()

        mean_loss_diff = x.mean()
        se_hac = newey_west_se(x, lags=lags)
        dm_stat = mean_loss_diff / se_hac if np.isfinite(se_hac) and se_hac > 0 else np.nan

        dm_results.append({
            "model_a": model_a,
            "model_b": model_b,
            "pair": f"{model_a} vs {model_b}",
            "T": len(x),
            "mean_loss_diff": mean_loss_diff,
            "nw_se": se_hac,
            "dm_stat": dm_stat,
            "lags": lags})

    dm_stats = pd.DataFrame(dm_results)

    return dm_stats, dm_monthly

# Clarke-West statistic
def cw_stat(df, y_col, yhat_col, date_col="date", lags=4):
    """
    Prints the Clark-West t-statistic using the zero-forecast benchmark.
    """
    d = df[[date_col, y_col, yhat_col]].dropna().copy()
    d[date_col] = pd.to_datetime(d[date_col])

    d["f_it"] = 2.0 * d[y_col] * d[yhat_col]

    f_t = d.groupby(date_col)["f_it"].mean().sort_index()

    mean_f = f_t.mean()
    se = newey_west_se(f_t, lags=lags)

    cw_t_stat = mean_f / se if np.isfinite(se) and se > 0 else np.nan

    print(f"CW t-stat: {cw_t_stat:.2f}")

    return cw_t_stat

#Variable importance
def compute_variable_importance(model, X_test, y_test, r2_func, zero_value=0.0):
    """
    Computes variable importance as the drop in out-of-sample R^2 when each
    characteristic is set to zero.
    """
    if len(X_test) == 0:
        return pd.Series(dtype=float)

    y_test = np.asarray(y_test, dtype=float)

    try:
        base_pred = model.predict(X_test, mean_factor=True)
    except TypeError:
        base_pred = model.predict(X_test)

    base_r2 = r2_func(y_test, base_pred)

    variable_importance = pd.Series(index=X_test.columns, dtype=float)

    for col in X_test.columns:
        X_zero = X_test.copy()
        X_zero[col] = zero_value

        try:
            pred_zero = model.predict(X_zero, mean_factor=True)
        except TypeError:
            pred_zero = model.predict(X_zero)

        r2_zero = r2_func(y_test, pred_zero)

        variable_importance[col] = base_r2 - r2_zero

    return variable_importance

# ------------------------------------------------------------------------------
# Robustness: winsorize
# ------------------------------------------------------------------------------
# Winsorize at the 5% level symmetrically, cross-sectionally each month
def winsorize_by_date(df, char_cols, date_col="date", lower_q=0.025, upper_q=0.975):
    def _winsorize_group(g):
        q_low = g[char_cols].quantile(lower_q)
        q_high = g[char_cols].quantile(upper_q)
        g[char_cols] = g[char_cols].clip(lower=q_low, upper=q_high, axis=1)
        return g

    return df.groupby(date_col, group_keys=False).apply(_winsorize_group)

# ------------------------------------------------------------------------------
# Robustness: Alternative characteristics library
# ------------------------------------------------------------------------------
# Full alternative characteristics list
char_cols_alternative = [
    "mvel1", "beta", "betasq", "chmom", "dolvol", "idiovol", "indmom","mom1m",
    "mom6m", "mom12m", "mom36m", "pricedelay", "turn", "absacc", "acc", "age",
    "agr", "bm", "bm_ia", "cashdebt", "cashpr", "cfp", "cfp_ia", "chatoia",
    "chcsho", "chempia", "chinv", "chpmia", "convind", "currat", "depr", "divi",
    "divo", "dy", "egr", "ep", "gma", "grcapx", "grltnoa", "herf", "hire",
    "invest", "lev", "lgr", "mve_ia", "operprof", "orgcap", "pchcapx_ia",
    "pchcurrat", "pchdepr", "pchgm_pchsale", "pchquick", "pchsale_pchinvt",
    "pchsale_pchrect", "pchsale_pchxsga", "pchsaleinv", "pctacc", "ps", "quick",
    "rd", "rd_mve", "rd_sale", "realestate", "roic", "salecash", "saleinv",
    "salerec", "secured", "securedind", "sgr", "sin", "sp", "tang", "tb",
    "aeavol", "cash", "chtx", "cinvest", "ear", "nincr", "roaq", "roavol",
    "roeq", "rsup", "stdacc", "stdcf", "ms", "baspread", "ill", "maxret",
    "retvol","std_dolvol", "std_turn", "zerotrade"]

"""# Core data pre-processing

Load core dataset from Jensen, et al. (2023)
"""

# Load core data
df_original = load_csv("Raw data/Jensen_core_characteristics.csv")

# Optimize data
df_original = optimize_df(df_original, cat_threshold=0.3)

# Set date variable
df_original["date"] = pd.to_datetime(df_original["date"].astype(str))

"""Dataframe metrics"""

print_dataframe_summary(df_original)

"""Create industry dummies"""

df_original = add_sic_dummies(df_original)

"""Clean dataset:
* Drop if "permno" is non-existent.
* Handling missing data.
* Rank normalization [-1,1].
"""

# Drop if "permno" is non-existent
drop_missing_rows(df_original, "permno")

# Handling missing data
print("-"*84)
df_original = impute_monthly_median(df_original, char_cols)

# Rank normalization [-1,1]
print("-"*84)
df_original = rank_normalize_characteristics(df_original, char_cols)

"""Merge with FF3-Factors"""

# Load FF3-Factor data
df_ff3 = load_csv("Raw data/FF3.csv")

# Optimize data
df_ff3 = optimize_df(df_ff3, cat_threshold=0.3)

# Set date variable
df_ff3 = df_ff3.rename(columns={'dateff': 'date'})
df_ff3["date"] = pd.to_datetime(df_ff3["date"].astype(str))

# Print dataframe metrics
print_dataframe_summary(df_ff3)

# Merging
df = pd.merge(df_original, df_ff3[["date", "mktrf", "smb", "hml", "rf"]], on="date", how="left")

# Print dataframe metrics
print("-"*84)
print_dataframe_summary(df)

"""Save processed data"""

# Optimize data before saving
df = optimize_df(df, cat_threshold=0.5)

# Save as .parquet file
save_parquet(df, "Processed data/df_processed.parquet", index=False, compression="snappy")

"""# Winsorized data pre-processing

Load core dataset from Jensen, et al. (2023)
"""

# Load core data
df_winsorized = load_csv("Raw data/Jensen_core_characteristics.csv")

# Optimize data
df_winsorized = optimize_df(df_winsorized, cat_threshold=0.3)

# Set date variable
df_winsorized["date"] = pd.to_datetime(df_winsorized["date"].astype(str))

"""Winsorizing at the 5% level, symmetrically"""

df_winsorized = winsorize_by_date(df_winsorized, char_cols)

"""Create industry dummies"""

df_winsorized = add_sic_dummies(df_winsorized)

"""Clean dataset:
* Drop if "permno" is non-existent.
* Handling missing data.
* Rank normalization [-1,1].
"""

# Drop if "permno" is non-existent
drop_missing_rows(df_winsorized, "permno")

# Handling missing data
print("-"*84)
df_winsorized = impute_monthly_median(df_winsorized, char_cols)

# Rank normalization [-1,1]
print("-"*84)
df_winsorized = rank_normalize_characteristics(df_winsorized, char_cols)

"""Save processed data"""

# Optimize data before saving
df_winsorized = optimize_df(df_winsorized, cat_threshold=0.5)

# Save as .parquet file
save_parquet(df_winsorized, "Processed data/df_processed_winsorized.parquet", index=False, compression="snappy")

"""# Alternative data pre-processing

Load alternative dataset from Gu, et al. (2020)
"""

# Load alternative data
df_alternative = load_csv("Raw data/Alternative_characteristics.csv")

# Optimize data
df_alternative = optimize_df(df_alternative, cat_threshold=0.3)

# Set date variable
df_alternative = df_alternative.rename(columns={"DATE" : "date"})
df_alternative["date"] = pd.to_datetime(df_alternative["date"].astype(str))

"""Dataframe metrics"""

print_dataframe_summary(df_alternative)

"""Merge with SIC"""

# Load SIC data
df_sic = load_csv("Raw data/SIC.csv")

# Optimize data
df_sic = optimize_df(df_sic, cat_threshold=0.3)

# Set date variable
df_sic["date"] = pd.to_datetime(df_sic["date"].astype(str))

# Print dataframe metrics
print_dataframe_summary(df_sic)

# Merging
df = pd.merge(df_alternative, df_sic[["permno","date","sic", "ret_exc"]], on=["permno","date"], how="left")

# Print dataframe metrics
print("-"*84)
print_dataframe_summary(df)

"""Create industry dummies"""

df = add_sic_dummies(df)

"""Clean dataset:
* Drop if "permno" is non-existent.
* Handling missing data.
* Rank normalization [-1,1].
"""

# Drop if "permno" is non-existent
drop_missing_rows(df, "permno")

# Handling missing data
print("-"*84)
df = impute_monthly_median(df, char_cols_alternative)

# Rank normalization [-1,1]
print("-"*84)
df = rank_normalize_characteristics(df, char_cols_alternative)

"""Save processed data"""

# Optimize data before saving
df = optimize_df(df, cat_threshold=0.5)

# Save as .parquet file
save_parquet(df, "Processed data/df_processed_alternative.parquet", index=False, compression="snappy")